services:
  product-service:
    build:
      context: ./ProductService
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=ProductDb;User=sa;Password=<123John@>;Encrypt=false;

  order-service:
    build:
      context: ./OrderService
    ports:
      - "8002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=OrderDb;User=sa;Password=<123John@>;Encrypt=false;
